Use the correct variable name: 'driver' instead of 'browser'
As it is now it fails with:

```
Traceback (most recent call last):
  File "./export.py", line 261, in <module>
    export(**vars(args))
  File "./export.py", line 182, in export
    driver = login(creds)
  File "./export.py", line 79, in login
    testHeader = browser.find_element_by_name('Header2Text')
NameError: global name 'browser' is not defined
```

This is because in this context the variable name is `driver` not `browser`